// script.js

// ================== STORAGE KEY ==================
const STORAGE_KEY = "ncdcShippingStateV2";

// ================== GLOBAL STATE =================
const appState = {
  orders: [],      // csv rows
  truckloads: [],  // physical trucks (auto or manual)
  history: [],
  team: [
    { name: "Router 1", role: "router", shift: "1st", active: true },
    { name: "Dock Lead", role: "dock", shift: "1st", active: true }
  ],
  settings: {
    maxLTL: 4,
    maxTL: 3,
    maxFloor: 2
  }
};

// ================== HELPERS =======================
function $(id) { return document.getElementById(id); }

function loadState() {
  try {
    const raw = localStorage.getItem(STORAGE_KEY);
    if (!raw) return;
    const parsed = JSON.parse(raw);
    Object.assign(appState, parsed);
  } catch (e) {
    console.warn("load failed", e);
  }
}

function saveState() {
  try {
    localStorage.setItem(STORAGE_KEY, JSON.stringify(appState));
  } catch (e) {
    console.warn("save failed", e);
  }
}

function mostCommon(arr) {
  const counts = {};
  let best = "";
  let max = 0;
  for (const v of arr) {
    const k = v || "";
    counts[k] = (counts[k] || 0) + 1;
    if (counts[k] > max) {
      max = counts[k];
      best = k;
    }
  }
  return best;
}

function sumNumber(rows, col) {
  return rows.reduce((sum, r) => {
    const n = Number((r[col] || "").toString().replace(/,/g, "")) || 0;
    return sum + n;
  }, 0);
}

function earliestDate(arr) {
  const dates = arr
    .map(d => d && d.trim())
    .filter(Boolean)
    .map(d => new Date(d));
  if (!dates.length) return "";
  dates.sort((a, b) => a - b);
  const first = dates[0];
  if (isNaN(first.getTime())) return "";
  return first.toISOString().slice(0, 10);
}

// ================== LOGIN (if present) ==============
const loginBtn = $("login-btn");
if (loginBtn) {
  loginBtn.addEventListener("click", () => {
    const loginEmail = $("login-email").value.trim();
    const loginPassword = $("login-password").value.trim();
    const ok =
      loginEmail === "htellez032003@gmail.com" &&
      loginPassword === "Ltapaprel040523";
    if (ok) {
      $("login-error").classList.add("hidden");
      $("login-screen").classList.add("hidden");
      $("app-shell").classList.remove("hidden");
    } else {
      $("login-error").classList.remove("hidden");
    }
  });
}

const logoutBtn = $("logout-btn");
if (logoutBtn) {
  logoutBtn.addEventListener("click", () => {
    $("app-shell").classList.add("hidden");
    $("login-screen").classList.remove("hidden");
  });
}

// ================== TABS ============================
const navLinks = document.querySelectorAll(".nav-link");
const tabPanels = document.querySelectorAll(".tab-panel");
navLinks.forEach(btn => {
  btn.addEventListener("click", () => {
    navLinks.forEach(b => b.classList.remove("active"));
    btn.classList.add("active");
    const tab = btn.dataset.tab;
    tabPanels.forEach(p => {
      if (p.id === "tab-" + tab) p.classList.remove("hidden");
      else p.classList.add("hidden");
    });
  });
});

// ================== CSV UPLOAD ======================
const csvInput = $("orders-csv");
if (csvInput) {
  csvInput.addEventListener("change", handleCSVUpload);
}

function handleCSVUpload(e) {
  const file = e.target.files[0];
  if (!file) return;
  const reader = new FileReader();
  reader.onload = evt => {
    const text = evt.target.result;
    parseCSV(text);
    if ($("csv-updated")) {
      $("csv-updated").textContent =
        "CSV updated: " + new Date().toLocaleString();
    }
  };
  reader.readAsText(file);
}

function parseCSV(text) {
  const lines = text.split(/\r?\n/).filter(l => l.trim() !== "");
  if (!lines.length) return;
  const header = lines[0].split(",").map(h => h.trim());
  const rows = lines.slice(1).map(line => {
    const cols = line.split(",");
    const obj = {};
    header.forEach((h, i) => {
      obj[h] = cols[i] ? cols[i].trim() : "";
    });
    return obj;
  });

  appState.orders = rows;

  // rebuild truckloads from CSV while preserving manual ones
  rebuildTruckloadsFromOrders();

  renderOrders();
  renderTruckloads();
  renderDock();
  renderTodays();
  renderTodaysFull();
  renderHistory();
  renderTeam();
  renderMetrics();
  saveState();
}

// ================== GROUPING ENGINE ==================
//
// Rules:
// 1. rows with Author#: 1 physical truck per Author#
// 2. rows without Author#: LTL bucket by (Shipper, Ready Date)
// 3. inside each load build nested: Master BOL# -> BOL# -> POs
//
function rebuildTruckloadsFromOrders() {
  const existingManual = appState.truckloads.filter(tl => !tl.autoGenerated);
  const autoLoads = [];

  // 1) rows with Author#
  const withAuthor = appState.orders.filter(o => (o["Author#"] || "").trim() !== "");
  const byAuthor = new Map();
  for (const o of withAuthor) {
    const author = (o["Author#"] || "").trim();
    if (!byAuthor.has(author)) byAuthor.set(author, []);
    byAuthor.get(author).push(o);
  }

  for (const [author, rows] of byAuthor.entries()) {
    autoLoads.push(buildLoadFromRows({
      loadId: author,
      rows,
      loadTypeHint: "Truckload" // can be Truckload or Floorload, CSV doesn't tell
    }));
  }

  // 2) rows without Author#  -> LTL
  const noAuthor = appState.orders.filter(o => (o["Author#"] || "").trim() === "");
  const ltlMap = new Map();
  for (const o of noAuthor) {
    const carrier = (o["Shipper"] || "").trim();
    const ready = (o["Ready Date"] || "").trim();
    if (!carrier || !ready) continue;
    const key = carrier + "||" + ready;
    if (!ltlMap.has(key)) ltlMap.set(key, []);
    ltlMap.get(key).push(o);
  }
  for (const [key, rows] of ltlMap.entries()) {
    autoLoads.push(buildLoadFromRows({
      loadId: "LTL-" + key,
      rows,
      loadTypeHint: "LTL"
    }));
  }

  // merge: manual loads stay, auto loads replace old auto loads entirely
  appState.truckloads = [...existingManual, ...autoLoads];
}

function buildLoadFromRows({ loadId, rows, loadTypeHint }) {
  const customer = mostCommon(rows.map(r => r["Cust Name"] || ""));
  const carrier = mostCommon(rows.map(r => r["Shipper"] || ""));
  const pickupDate = earliestDate(rows.map(r => r["Ready Date"] || ""));
  const bolCommon = mostCommon(rows.map(r => r["BOL#"] || ""));
  const cartons = sumNumber(rows, "Est. Cartons");
  const pallets = sumNumber(rows, "Est. Pallet");
  const weight = sumNumber(rows, "Total Weight");
  const cube = sumNumber(rows, "Total Cubic");

  // build nested master->bol->po
  const masterGroups = buildMasterGroups(rows);

  return {
    loadId,
    autoGenerated: true,
    loadType: loadTypeHint || "Truckload",
    customer,
    carrier,
    pickupDate,
    bol: bolCommon,
    cartons,
    pallets,
    weight,
    cube,
    stagedLocation: "",
    assignedTo: "",
    status: "Unstaged",
    masterGroups,
    departed: false
  };
}

function buildMasterGroups(rows) {
  // group by Master BOL# first
  const byMaster = new Map();
  for (const r of rows) {
    const mbol = (r["Master BOL#"] || "").trim();
    const list = byMaster.get(mbol) || [];
    list.push(r);
    byMaster.set(mbol, list);
  }

  const result = [];
  for (const [mbol, mrows] of byMaster.entries()) {
    // inside master, group by BOL#
    const byBol = new Map();
    for (const r of mrows) {
      const bol = (r["BOL#"] || "").trim();
      const blist = byBol.get(bol) || [];
      blist.push(r);
      byBol.set(bol, blist);
    }
    const bols = [];
    for (const [bol, bRows] of byBol.entries()) {
      bols.push({
        bol,
        pos: bRows.map(r => ({
          po: r["PO Num"] || "",
          customer: r["Cust Name"] || "",
          cartons: Number(r["Est. Cartons"] || 0),
          pallets: Number(r["Est. Pallet"] || 0)
        }))
      });
    }
    result.push({
      masterBol: mbol, // can be "" if none
      bols
    });
  }
  return result;
}

// ================== ORDERS RENDER ===================
const selectedPOs = new Set();
let filteredOrders = [];

function renderOrders() {
  const ordersBody = $("orders-body");
  if (!ordersBody) return;

  if (!filteredOrders.length) filteredOrders = appState.orders.slice();

  ordersBody.innerHTML = "";
  filteredOrders.forEach(o => {
    const po = o["PO Num"] || "";
    const tr = document.createElement("tr");
    tr.innerHTML = `
      <td><input type="checkbox" class="po-check" data-po="${po}" ${selectedPOs.has(po) ? "checked" : ""}></td>
      <td>${o["Division"] || ""}</td>
      <td>${o["BOL#"] || ""}</td>
      <td>${o["Master BOL#"] || ""}</td>
      <td>${po}</td>
      <td>${o["Customer"] || ""}</td>
      <td>${o["Cust Name"] || ""}</td>
      <td>${o["Shipper"] || ""}</td>
      <td>${o["TTL QTY"] || ""}</td>
      <td>${o["TTL Amt"] || ""}</td>
      <td>${o["Total Weight"] || ""}</td>
      <td>${o["Total Cubic"] || ""}</td>
      <td>${o["Est. Cartons"] || ""}</td>
      <td>${o["Est. Pallet"] || ""}</td>
      <td>${o["Pick Proc Date"] || ""}</td>
      <td>${o["Start Date"] || ""}</td>
      <td>${o["Cancel Date"] || ""}</td>
      <td>${o["Router"] || ""}</td>
      <td>${o["Route Date"] || ""}</td>
      <td>${o["Scheduled Date"] || ""}</td>
      <td>${o["Ready Date"] || ""}</td>
      <td>${o["Author#"] || ""}</td>
      <td>${o["PT STATUS"] || ""}</td>
      <td></td>
    `;
    ordersBody.appendChild(tr);
  });

  document.querySelectorAll(".po-check").forEach(chk => {
    chk.addEventListener("change", e => {
      const po = e.target.dataset.po;
      if (e.target.checked) selectedPOs.add(po);
      else selectedPOs.delete(po);
      updateSelectedCount();
    });
  });

  updateSelectedCount();
}

function updateSelectedCount() {
  const el = $("selected-count");
  if (el) el.textContent = selectedPOs.size;
}

const ordersSearch = $("orders-search");
if (ordersSearch) {
  ordersSearch.addEventListener("input", e => {
    const q = e.target.value.toLowerCase();
    filteredOrders = appState.orders.filter(o => {
      return (
        (o["PO Num"] || "").toLowerCase().includes(q) ||
        (o["Cust Name"] || "").toLowerCase().includes(q) ||
        (o["Customer"] || "").toLowerCase().includes(q) ||
        (o["Shipper"] || "").toLowerCase().includes(q) ||
        (o["BOL#"] || "").toLowerCase().includes(q)
      );
    });
    renderOrders();
  });
}

const applyDate = $("apply-date-filter");
if (applyDate) {
  applyDate.addEventListener("click", () => {
    const col = $("date-column-select").value;
    const from = $("date-from").value;
    const to = $("date-to").value;
    filteredOrders = appState.orders.filter(o => {
      const v = (o[col] || "").split(" ")[0];
      if (!v) return false;
      if (from && v < from) return false;
      if (to && v > to) return false;
      return true;
    });
    renderOrders();
  });
}

const clearFilters = $("clear-filters");
if (clearFilters) {
  clearFilters.addEventListener("click", () => {
    filteredOrders = appState.orders.slice();
    if ($("orders-search")) $("orders-search").value = "";
    if ($("date-from")) $("date-from").value = "";
    if ($("date-to")) $("date-to").value = "";
    renderOrders();
  });
}

const selectAllOrders = $("select-all-orders");
if (selectAllOrders) {
  selectAllOrders.addEventListener("change", e => {
    const checked = e.target.checked;
    document.querySelectorAll("#orders-body .po-check").forEach(chk => {
      chk.checked = checked;
      const po = chk.dataset.po;
      if (checked) selectedPOs.add(po);
      else selectedPOs.delete(po);
    });
    updateSelectedCount();
  });
}

// ================== SIMPLE CALENDAR =====================
const calendarEl = $("orders-calendar");
const calendarDetail = $("calendar-detail");
if (calendarEl) {
  calendarEl.innerHTML = "";
  for (let d = 1; d <= 30; d++) {
    const btn = document.createElement("button");
    btn.textContent = d;
    btn.addEventListener("click", () => {
      if (calendarDetail) {
        calendarDetail.textContent =
          "Availability for day " + d + " – LTL/TL/Floorload slots.";
      }
    });
    calendarEl.appendChild(btn);
  }
}

// ================== MANUAL TRUCKLOAD MODAL ==============
const createTLBtn = $("create-truckload-btn");
const modalOverlay = $("modal-overlay");
if (createTLBtn && modalOverlay) {
  createTLBtn.addEventListener("click", () => {
    if (selectedPOs.size === 0) {
      alert("Select at least one PO line first.");
      return;
    }
    $("modal-selected-pos").textContent =
      "POs: " + Array.from(selectedPOs).join(", ");
    modalOverlay.classList.remove("hidden");
  });
}
const tlCancel = $("tl-cancel");
if (tlCancel && modalOverlay) {
  tlCancel.addEventListener("click", () => {
    modalOverlay.classList.add("hidden");
  });
}
const tlSave = $("tl-save");
if (tlSave && modalOverlay) {
  tlSave.addEventListener("click", () => {
    const loadId =
      $("tl-load-id").value.trim() ||
      "LOAD-" + (appState.truckloads.length + 1);
    const tl = {
      loadId,
      autoGenerated: false,
      loadType: $("tl-load-type").value,
      pickupDate: $("tl-pickup-date").value,
      carrier: $("tl-carrier").value,
      customer: $("tl-customer").value,
      bol: $("tl-bol").value,
      cartons: Number($("tl-cartons").value) || 0,
      pallets: Number($("tl-pallets").value) || 0,
      weight: 0,
      cube: 0,
      stagedLocation: "",
      assignedTo: "",
      status: "Unstaged",
      masterGroups: [],
      departed: false
    };
    appState.truckloads.push(tl);
    renderTruckloads();
    renderDock();
    renderTodays();
    renderTodaysFull();
    renderMetrics();
    saveState();
    modalOverlay.classList.add("hidden");
  });
}

// ================== DOCK RENDER =========================
function renderDock() {
  const dockBody = $("dock-body");
  const dockPreviewBody = $("dock-preview-body");
  if (dockBody) dockBody.innerHTML = "";
  if (dockPreviewBody) dockPreviewBody.innerHTML = "";

  appState.truckloads.forEach(tl => {
    const row = `
      <td>${tl.loadId}</td>
      <td>${tl.customer || ""}</td>
      <td>${tl.carrier || ""}</td>
      <td>${tl.loadType || ""}</td>
      <td>${tl.pickupDate || ""}</td>
      <td>${tl.cartons || 0}</td>
      <td>${tl.pallets || 0}</td>
      <td>${tl.stagedLocation || ""}</td>
      <td>${tl.assignedTo || ""}</td>
      <td>${tl.status || ""}</td>
    `;
    if (dockBody) {
      const tr = document.createElement("tr");
      tr.innerHTML =
        row +
        `<td>
          <button class="btn tiny" data-assign="${tl.loadId}">Assign</button>
          <button class="btn tiny secondary" data-stage="${tl.loadId}">Fully Staged</button>
        </td>`;
      dockBody.appendChild(tr);
    }
    if (dockPreviewBody) {
      const tr2 = document.createElement("tr");
      tr2.innerHTML = row;
      dockPreviewBody.appendChild(tr2);
    }
  });

  document.querySelectorAll("[data-assign]").forEach(btn => {
    btn.addEventListener("click", () => {
      const id = btn.dataset.assign;
      const who = prompt("Assign to who?");
      const tl = appState.truckloads.find(t => t.loadId === id);
      if (tl) {
        tl.assignedTo = who || "";
        tl.status = "Being staged";
        renderDock();
        renderTodays();
        renderTodaysFull();
        renderMetrics();
        saveState();
      }
    });
  });
  document.querySelectorAll("[data-stage]").forEach(btn => {
    btn.addEventListener("click", () => {
      const id = btn.dataset.stage;
      const tl = appState.truckloads.find(t => t.loadId === id);
      if (tl) {
        tl.status = "Fully staged";
        renderDock();
        renderTodays();
        renderTodaysFull();
        renderMetrics();
        saveState();
      }
    });
  });
}

// ================== TODAY'S PICKUPS ====================
function renderTodays() {
  const body = $("today-body");
  if (!body) return;
  body.innerHTML = "";

  let totalTrucks = 0, atDoor = 0, departed = 0, totalCartons = 0;

  appState.truckloads.forEach(tl => {
    totalTrucks++;
    totalCartons += tl.cartons || 0;
    if (tl.status === "At door") atDoor++;
    if (tl.status === "Departed") departed++;

    const tr = document.createElement("tr");
    tr.innerHTML = `
      <td>${tl.loadId}</td>
      <td>${tl.customer || ""}</td>
      <td>${tl.carrier || ""}</td>
      <td>${tl.loadType || ""}</td>
      <td>${tl.pickupDate || ""}</td>
      <td>${tl.cartons || 0}</td>
      <td>${tl.status || ""}</td>
      <td><button class="btn tiny" data-arrived="${tl.loadId}">Arrived</button></td>
      <td><button class="btn tiny secondary" data-departed="${tl.loadId}">Departed</button></td>
    `;
    body.appendChild(tr);
  });

  if ($("tp-total-trucks")) $("tp-total-trucks").textContent = totalTrucks;
  if ($("tp-at-door")) $("tp-at-door").textContent = atDoor;
  if ($("tp-departed")) $("tp-departed").textContent = departed;
  if ($("tp-cartons")) $("tp-cartons").textContent = totalCartons;
  if ($("tp-dollars")) $("tp-dollars").textContent = "$0";

  attachArrivedDeparted();
}

function renderTodaysFull() {
  const body = $("today-full-body");
  if (!body) return;
  body.innerHTML = "";
  appState.truckloads.forEach(tl => {
    const tr = document.createElement("tr");
    tr.innerHTML = `
      <td>${tl.loadId}</td>
      <td>${tl.customer || ""}</td>
      <td>${tl.carrier || ""}</td>
      <td>${tl.loadType || ""}</td>
      <td>${tl.pickupDate || ""}</td>
      <td>${tl.cartons || 0}</td>
      <td>${tl.status || ""}</td>
      <td><button class="btn tiny" data-arrived="${tl.loadId}">Arrived</button></td>
      <td><button class="btn tiny secondary" data-departed="${tl.loadId}">Departed</button></td>
    `;
    body.appendChild(tr);
  });
  attachArrivedDeparted();
}

function attachArrivedDeparted() {
  document.querySelectorAll("[data-arrived]").forEach(btn => {
    btn.addEventListener("click", () => {
      const id = btn.dataset.arrived;
      const tl = appState.truckloads.find(t => t.loadId === id);
      if (tl) {
        tl.status = "At door";
        renderTodays();
        renderTodaysFull();
        renderMetrics();
        saveState();
      }
    });
  });
  document.querySelectorAll("[data-departed]").forEach(btn => {
    btn.addEventListener("click", () => {
      const id = btn.dataset.departed;
      const tl = appState.truckloads.find(t => t.loadId === id);
      if (tl) {
        tl.status = "Departed";
        tl.departed = true;
        appState.history.push({
          loadId: tl.loadId,
          customer: tl.customer,
          carrier: tl.carrier,
          pickupDate: tl.pickupDate,
          bol: tl.bol,
          status: "Departed"
        });
        renderTodays();
        renderTodaysFull();
        renderHistory();
        renderMetrics();
        saveState();
      }
    });
  });
}

// ================== TRUCKLOADS TAB ====================
function renderTruckloads() {
  const body = $("truckloads-body");
  const bodyFull = $("truckloads-full-body");
  if (body) body.innerHTML = "";
  if (bodyFull) bodyFull.innerHTML = "";

  appState.truckloads.forEach(tl => {
    if (body) {
      const tr = document.createElement("tr");
      tr.innerHTML = `
        <td>${tl.loadId}</td>
        <td>${tl.customer || ""}</td>
        <td>${tl.carrier || ""}</td>
        <td>${tl.loadType || ""}</td>
        <td>${tl.pickupDate || ""}</td>
        <td>${tl.cartons || 0}</td>
        <td>${tl.status || ""}</td>
      `;
      body.appendChild(tr);
    }
    if (bodyFull) {
      const tr2 = document.createElement("tr");
      tr2.innerHTML = `
        <td>${tl.loadId}</td>
        <td>${tl.customer || ""}</td>
        <td>${tl.carrier || ""}</td>
        <td>${tl.loadType || ""}</td>
        <td>${tl.pickupDate || ""}</td>
        <td>${tl.weight || ""}</td>
        <td>${tl.cube || ""}</td>
        <td>${tl.cartons || 0}</td>
        <td>${tl.pallets || 0}</td>
        <td>${tl.stagedLocation || ""}</td>
        <td>${tl.status || ""}</td>
      `;
      bodyFull.appendChild(tr2);
    }
  });
}

// ================== HISTORY ===========================
function renderHistory() {
  const body = $("history-body");
  if (!body) return;
  body.innerHTML = "";
  appState.history.forEach(h => {
    const tr = document.createElement("tr");
    tr.innerHTML = `
      <td>${h.loadId}</td>
      <td>${h.customer || ""}</td>
      <td>${h.carrier || ""}</td>
      <td>${h.pickupDate || ""}</td>
      <td>${h.bol || ""}</td>
      <td>${h.status}</td>
    `;
    body.appendChild(tr);
  });
}

// ================== TEAM =============================
function renderTeam() {
  const body = $("team-body");
  if (!body) return;
  body.innerHTML = "";
  appState.team.forEach(t => {
    const tr = document.createElement("tr");
    tr.innerHTML = `
      <td>${t.name}</td>
      <td>${t.role}</td>
      <td>${t.shift}</td>
      <td>${t.active ? "Yes" : "No"}</td>
    `;
    body.appendChild(tr);
  });
}

// ================== METRICS ===========================
function renderMetrics() {
  const mTrucksToday = $("m-trucks-today");
  const mCartons = $("m-cartons");
  const mStaged = $("m-staged");

  const loads = appState.truckloads;
  const trucks = loads.length;
  const cartons = loads.reduce((s, tl) => s + (tl.cartons || 0), 0);
  const staged = loads.filter(tl => tl.status === "Fully staged").length;

  if (mTrucksToday) mTrucksToday.textContent = trucks;
  if (mCartons) mCartons.textContent = cartons;
  if (mStaged) mStaged.textContent = staged;
}

// ================== EXPORT BUTTONS ====================
const metricsExportBtn = $("metrics-export");
if (metricsExportBtn) {
  metricsExportBtn.addEventListener("click", () => {
    const rows = [
      ["Metric","Value"],
      ["Trucks", appState.truckloads.length],
      ["Departed", appState.history.length]
    ];
    downloadCSV("metrics.csv", rows);
  });
}

const exportCsv = $("export-csv");
if (exportCsv) {
  exportCsv.addEventListener("click", () => {
    exportTruckloads("truckloads-preview.csv");
  });
}
const exportCsvFull = $("export-csv-full");
if (exportCsvFull) {
  exportCsvFull.addEventListener("click", () => {
    exportTruckloads("truckloads.csv");
  });
}

function exportTruckloads(filename) {
  const rows = [
    ["Load ID","Customer","Carrier","Load Type","Pick Up Date","Total Cartons","Status"]
  ];
  appState.truckloads.forEach(tl => {
    rows.push([
      tl.loadId,
      tl.customer || "",
      tl.carrier || "",
      tl.loadType || "",
      tl.pickupDate || "",
      tl.cartons || 0,
      tl.status || ""
    ]);
  });
  downloadCSV(filename, rows);
}

function downloadCSV(filename, rows) {
  const csvContent = rows.map(r => r.map(v => `"${v}"`).join(",")).join("\n");
  const blob = new Blob([csvContent], { type: "text/csv;charset=utf-8;" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  a.click();
  URL.revokeObjectURL(url);
}

// ================== INIT =============================
(function init() {
  loadState();
  renderOrders();
  renderTruckloads();
  renderDock();
  renderTodays();
  renderTodaysFull();
  renderHistory();
  renderTeam();
  renderMetrics();
})();
