// script.js  (final with drill-down)

// ===== STORAGE KEY =====
const STORAGE_KEY = "ncdcShippingStateV2";

// ===== STATE =====
const appState = {
  orders: [],
  truckloads: [],
  history: [],
  team: [
    { name: "Router 1", role: "router", shift: "1st", active: true },
    { name: "Dock Lead", role: "dock", shift: "1st", active: true }
  ],
  settings: { maxLTL: 4, maxTL: 3, maxFloor: 2 }
};

// ===== UTILS =====
function $(id) { return document.getElementById(id); }

function loadState() {
  try { Object.assign(appState, JSON.parse(localStorage.getItem(STORAGE_KEY) || "{}")); }
  catch {}
}

function saveState() {
  try { localStorage.setItem(STORAGE_KEY, JSON.stringify(appState)); }
  catch {}
}

function mostCommon(a){const c={};let m="",n=0;for(const v of a){const k=v||"";c[k]=(c[k]||0)+1;if(c[k]>n){n=c[k];m=k}}return m;}
function sumNumber(r,c){return r.reduce((s,x)=>s+(+((x[c]||"").replace(/,/g,""))||0),0);}
function earliestDate(a){const d=a.map(x=>x&&new Date(x)).filter(x=>x&&x>0);if(!d.length)return"";d.sort((a,b)=>a-b);return d[0].toISOString().slice(0,10);}

// ===== LOGIN (if present) =====
if ($("login-btn")) {
  $("login-btn").onclick = () => {
    const ok = $("login-email").value.trim()==="htellez032003@gmail.com" &&
               $("login-password").value.trim()==="Ltapaprel040523";
    if (ok){$("login-error").classList.add("hidden");$("login-screen").classList.add("hidden");$("app-shell").classList.remove("hidden");}
    else {$("login-error").classList.remove("hidden");}
  };
}
if ($("logout-btn")) $("logout-btn").onclick=()=>{$("app-shell").classList.add("hidden");$("login-screen").classList.remove("hidden");};

// ===== NAV =====
document.querySelectorAll(".nav-link").forEach(b=>b.onclick=()=>{
  document.querySelectorAll(".nav-link").forEach(x=>x.classList.remove("active"));
  b.classList.add("active");
  const t=b.dataset.tab;
  document.querySelectorAll(".tab-panel").forEach(p=>p.classList.toggle("hidden",p.id!=="tab-"+t));
});

// ===== CSV UPLOAD =====
if ($("orders-csv")) $("orders-csv").addEventListener("change",e=>{
  const f=e.target.files[0];if(!f)return;
  const r=new FileReader();
  r.onload=ev=>{parseCSV(ev.target.result);$("csv-updated").textContent="CSV updated: "+new Date().toLocaleString();};
  r.readAsText(f);
});

function parseCSV(txt){
  const lines=txt.split(/\r?\n/).filter(l=>l.trim()!=="");
  if(!lines.length)return;
  const h=lines[0].split(",").map(x=>x.trim());
  const rows=lines.slice(1).map(l=>{
    const c=l.split(",");
    const o={};h.forEach((hh,i)=>o[hh]=c[i]?c[i].trim():"");
    return o;
  });
  appState.orders=rows;
  rebuildTruckloadsFromOrders();
  renderAll(); saveState();
}

// ===== GROUPING =====
function rebuildTruckloadsFromOrders(){
  const manual=appState.truckloads.filter(t=>!t.autoGenerated);
  const auto=[];
  const withAuth=appState.orders.filter(o=>(o["Author#"]||"").trim());
  const byAuth=new Map();
  for(const o of withAuth){const a=o["Author#"].trim();if(!byAuth.has(a))byAuth.set(a,[]);byAuth.get(a).push(o);}
  for(const [a,rows]of byAuth)auto.push(buildLoadFromRows({loadId:a,rows,loadTypeHint:"Truckload"}));

  const noAuth=appState.orders.filter(o=>!(o["Author#"]||"").trim());
  const ltlMap=new Map();
  for(const o of noAuth){
    const k=(o["Shipper"]||"").trim()+"||"+(o["Ready Date"]||"").trim();
    if(!ltlMap.has(k))ltlMap.set(k,[]);
    ltlMap.get(k).push(o);
  }
  for(const [k,rows]of ltlMap)auto.push(buildLoadFromRows({loadId:"LTL-"+k,rows,loadTypeHint:"LTL"}));
  appState.truckloads=[...manual,...auto];
}

function buildLoadFromRows({loadId,rows,loadTypeHint}){
  const customer=mostCommon(rows.map(r=>r["Cust Name"]||""));
  const carrier=mostCommon(rows.map(r=>r["Shipper"]||""));
  const pickupDate=earliestDate(rows.map(r=>r["Ready Date"]||""));
  const bolCommon=mostCommon(rows.map(r=>r["BOL#"]||""));
  const cartons=sumNumber(rows,"Est. Cartons");
  const pallets=sumNumber(rows,"Est. Pallet");
  const weight=sumNumber(rows,"Total Weight");
  const cube=sumNumber(rows,"Total Cubic");
  const masterGroups=buildMasterGroups(rows);
  return{loadId,autoGenerated:true,loadType:loadTypeHint||"Truckload",customer,carrier,pickupDate,bol:bolCommon,
    cartons,pallets,weight,cube,stagedLocation:"",assignedTo:"",status:"Unstaged",masterGroups,departed:false};
}

function buildMasterGroups(rows){
  const byM=new Map();
  for(const r of rows){const m=(r["Master BOL#"]||"").trim();if(!byM.has(m))byM.set(m,[]);byM.get(m).push(r);}
  const res=[];
  for(const [m,rs]of byM){
    const byB=new Map();
    for(const r of rs){const b=(r["BOL#"]||"").trim();if(!byB.has(b))byB.set(b,[]);byB.get(b).push(r);}
    const bols=[];
    for(const [b,bs]of byB){
      bols.push({bol:b,pos:bs.map(x=>({po:x["PO Num"],customer:x["Cust Name"],cartons:+(x["Est. Cartons"]||0),pallets:+(x["Est. Pallet"]||0)}))});
    }
    res.push({masterBol:m,bols});
  }
  return res;
}

// ===== ORDERS =====
let filteredOrders=[];const selectedPOs=new Set();
function renderOrders(){
  const tb=$("orders-body");if(!tb)return;
  if(!filteredOrders.length)filteredOrders=[...appState.orders];
  tb.innerHTML="";
  for(const o of filteredOrders){
    const po=o["PO Num"]||"";
    tb.insertAdjacentHTML("beforeend",`
      <tr>
        <td><input type="checkbox" class="po-check" data-po="${po}" ${selectedPOs.has(po)?"checked":""}></td>
        <td>${o["Division"]||""}</td><td>${o["BOL#"]||""}</td><td>${o["Master BOL#"]||""}</td>
        <td>${po}</td><td>${o["Customer"]||""}</td><td>${o["Cust Name"]||""}</td><td>${o["Shipper"]||""}</td>
        <td>${o["TTL QTY"]||""}</td><td>${o["TTL Amt"]||""}</td><td>${o["Total Weight"]||""}</td>
        <td>${o["Total Cubic"]||""}</td><td>${o["Est. Cartons"]||""}</td><td>${o["Est. Pallet"]||""}</td>
        <td>${o["Pick Proc Date"]||""}</td><td>${o["Start Date"]||""}</td><td>${o["Cancel Date"]||""}</td>
        <td>${o["Router"]||""}</td><td>${o["Route Date"]||""}</td><td>${o["Scheduled Date"]||""}</td>
        <td>${o["Ready Date"]||""}</td><td>${o["Author#"]||""}</td><td>${o["PT STATUS"]||""}</td><td></td>
      </tr>`);
  }
  document.querySelectorAll(".po-check").forEach(ch=>ch.onchange=e=>{
    const p=e.target.dataset.po;if(e.target.checked)selectedPOs.add(p);else selectedPOs.delete(p);
    $("selected-count").textContent=selectedPOs.size;
  });
}

// ===== CALENDAR dummy =====
if ($("orders-calendar")){for(let i=1;i<=30;i++){const b=document.createElement("button");b.textContent=i;$("orders-calendar").appendChild(b);}}

// ===== MANUAL LOAD MODAL =====
if ($("create-truckload-btn")) $("create-truckload-btn").onclick=()=>{
  if(!selectedPOs.size)return alert("Select at least one PO.");
  $("modal-selected-pos").textContent="POs: "+[...selectedPOs].join(", ");
  $("modal-overlay").classList.remove("hidden");
};
if ($("tl-cancel")) $("tl-cancel").onclick=()=>$("modal-overlay").classList.add("hidden");
if ($("tl-save")) $("tl-save").onclick=()=>{
  const id=$("tl-load-id").value.trim()||"LOAD-"+(appState.truckloads.length+1);
  appState.truckloads.push({loadId:id,autoGenerated:false,loadType:$("tl-load-type").value,
    pickupDate:$("tl-pickup-date").value,carrier:$("tl-carrier").value,customer:$("tl-customer").value,
    bol:$("tl-bol").value,cartons:+$("tl-cartons").value||0,pallets:+$("tl-pallets").value||0,
    weight:0,cube:0,status:"Unstaged",assignedTo:"",stagedLocation:"",masterGroups:[],departed:false});
  $("modal-overlay").classList.add("hidden");renderAll();saveState();
};

// ===== DOCK / TODAY / HISTORY / METRICS short renders =====
function renderDock(){
  const b=$("dock-body");if(!b)return;b.innerHTML="";
  for(const t of appState.truckloads){
    b.insertAdjacentHTML("beforeend",`
      <tr><td>${t.loadId}</td><td>${t.customer||""}</td><td>${t.carrier||""}</td>
      <td>${t.loadType||""}</td><td>${t.pickupDate||""}</td><td>${t.cartons||0}</td><td>${t.pallets||0}</td>
      <td>${t.stagedLocation||""}</td><td>${t.assignedTo||""}</td><td>${t.status||""}</td>
      <td><button class="btn tiny" data-assign="${t.loadId}">Assign</button>
      <button class="btn tiny secondary" data-stage="${t.loadId}">Fully Staged</button></td></tr>`);
  }
  document.querySelectorAll("[data-assign]").forEach(b=>b.onclick=()=>{
    const id=b.dataset.assign;const t=appState.truckloads.find(x=>x.loadId===id);
    if(!t)return;const who=prompt("Assign to who?");t.assignedTo=who||"";t.status="Being staged";renderAll();saveState();
  });
  document.querySelectorAll("[data-stage]").forEach(b=>b.onclick=()=>{
    const id=b.dataset.stage;const t=appState.truckloads.find(x=>x.loadId===id);
    if(!t)return;t.status="Fully staged";renderAll();saveState();
  });
}
function renderTodays(){const b=$("today-body");if(!b)return;b.innerHTML="";
  for(const t of appState.truckloads){
    b.insertAdjacentHTML("beforeend",`<tr><td>${t.loadId}</td><td>${t.customer||""}</td><td>${t.carrier||""}</td>
      <td>${t.loadType||""}</td><td>${t.pickupDate||""}</td><td>${t.cartons||0}</td><td>${t.status||""}</td>
      <td><button class="btn tiny" data-arrived="${t.loadId}">Arrived</button></td>
      <td><button class="btn tiny secondary" data-departed="${t.loadId}">Departed</button></td></tr>`);
  }
  document.querySelectorAll("[data-arrived]").forEach(b=>b.onclick=()=>{
    const t=appState.truckloads.find(x=>x.loadId===b.dataset.arrived);if(t){t.status="At door";renderAll();saveState();}});
  document.querySelectorAll("[data-departed]").forEach(b=>b.onclick=()=>{
    const t=appState.truckloads.find(x=>x.loadId===b.dataset.departed);
    if(t){t.status="Departed";appState.history.push({loadId:t.loadId,customer:t.customer,carrier:t.carrier,pickupDate:t.pickupDate,bol:t.bol,status:"Departed"});renderAll();saveState();}});
}
function renderHistory(){const b=$("history-body");if(!b)return;b.innerHTML="";
  for(const h of appState.history)b.insertAdjacentHTML("beforeend",`<tr><td>${h.loadId}</td><td>${h.customer||""}</td><td>${h.carrier||""}</td><td>${h.pickupDate||""}</td><td>${h.bol||""}</td><td>${h.status}</td></tr>`);
}
function renderMetrics(){
  if($("m-trucks-today"))$("m-trucks-today").textContent=appState.truckloads.length;
  if($("m-cartons"))$("m-cartons").textContent=appState.truckloads.reduce((s,t)=>s+(t.cartons||0),0);
  if($("m-staged"))$("m-staged").textContent=appState.truckloads.filter(t=>t.status==="Fully staged").length;
}

// ===== TRUCKLOADS + DRILL-DOWN =====
function renderTruckloads(){
  const b=$("truckloads-body");if(!b)return;b.innerHTML="";
  for(const t of appState.truckloads){
    b.insertAdjacentHTML("beforeend",`<tr class="tl-row" data-id="${t.loadId}">
      <td>${t.loadId}</td><td>${t.customer||""}</td><td>${t.carrier||""}</td>
      <td>${t.loadType||""}</td><td>${t.pickupDate||""}</td><td>${t.cartons||0}</td><td>${t.status||""}</td></tr>`);
  }
  // drill-down wiring
  document.querySelectorAll(".tl-row").forEach(row=>row.onclick=()=>{
    const id=row.dataset.id;
    const load=appState.truckloads.find(t=>t.loadId===id);
    if(!load)return;
    const b=document.getElementById("tl-detail-body");
    b.innerHTML=load.masterGroups.map(m=>
      `<div><strong>Master BOL:</strong> ${m.masterBol||"(none)"}<ul>`+
      m.bols.map(bl=>`<li><strong>${bl.bol||"(no BOL)"}:</strong> ${bl.pos.map(p=>p.po).join(", ")}</li>`).join("")+
      `</ul></div>`
    ).join("");
    document.getElementById("tl-detail-title").textContent=`${load.loadId} — ${load.customer||""}`;
    document.getElementById("tl-detail-overlay").classList.remove("hidden");
  });
}

// ===== RENDER ALL =====
function renderAll(){renderOrders();renderTruckloads();renderDock();renderTodays();renderHistory();renderMetrics();}

// ===== INIT =====
loadState();renderAll();
